# Default application configuration
# This file contains default settings that apply to all environments
# Environment-specific overrides should be placed in application-{env}.yaml files

# Application metadata
application:
  name: Trading Platform
  version: 2.0.0
  description: OOP-based trading platform with domain-driven design

# Environment settings (can be overridden)
environment: development

# Multiple database configurations for different domains
database:
  # Primary database for market data
  primary:
    type: postgresql
    host: localhost
    port: 5432
    name: markets_technicals
    user: postgres
    password: ${TRADING_DB_PASSWORD:root}
    
    # Connection pool settings
    pool:
      size: 5
      max_overflow: 10
      timeout: 30
      recycle: 3600
      pre_ping: true
    
    # SSL settings (for production)
    ssl:
      enabled: false
      mode: require
      ca_cert: null
  
  # Technical analysis database
  technical_analysis:
    type: postgresql
    host: localhost
    port: 5432
    name: markets_technicals
    user: postgres
    password: ${TRADING_DB_PASSWORD:root}
    pool:
      size: 10
      max_overflow: 20
      timeout: 30
      recycle: 3600
      pre_ping: true
  
  # Market internals database
  internals:
    type: postgresql
    host: localhost
    port: 5432
    name: markets_internals
    user: postgres
    password: ${TRADING_DB_PASSWORD:root}
    pool:
      size: 5
      max_overflow: 10
      timeout: 30
      recycle: 3600
      pre_ping: true
  
  # Fundamentals database
  fundamentals:
    type: postgresql
    host: localhost
    port: 5432
    name: markets_fundamentals
    user: postgres
    password: ${TRADING_DB_PASSWORD:root}
    pool:
      size: 5
      max_overflow: 10
      timeout: 30
      recycle: 3600
      pre_ping: true
  
  # Macro economic data database
  macro:
    type: postgresql
    host: localhost
    port: 5432
    name: markets_macro
    user: postgres
    password: ${TRADING_DB_PASSWORD:root}
    pool:
      size: 3
      max_overflow: 5
      timeout: 30
      recycle: 3600
      pre_ping: true
  
  # Plurality/WAMRS database
  plurality:
    type: postgresql
    host: localhost
    port: 5432
    name: Plurality
    user: postgres
    password: ${TRADING_DB_PASSWORD:root}
    pool:
      size: 5
      max_overflow: 10
      timeout: 30
      recycle: 3600
      pre_ping: true
  
  # Backtesting results database
  backtesting:
    type: postgresql
    host: localhost
    port: 5432
    name: backtesting_results
    user: postgres
    password: ${TRADING_DB_PASSWORD:root}
    pool:
      size: 3
      max_overflow: 5
      timeout: 30
      recycle: 3600
      pre_ping: true

# Data provider configurations
data_providers:
  iqfeed:
    type: iqfeed
    enabled: true
    primary: true
    host: 127.0.0.1
    
    # Service ports
    ports:
      level1: 5009
      lookup: 9100
      level2: 9200
      admin: 9300
      derivative: 9400
    
    # Credentials (use environment variables in production)
    credentials:
      username: ${IQFEED_USERNAME:}
      password: ${IQFEED_PASSWORD:}
    
    # Product information
    product_id: ${IQFEED_PRODUCT_ID:}
    product_version: 1.0
    requires_product_id: false
    
    # Data retrieval settings
    limits:
      max_symbols: 500
      max_days: 365
      chunk_size: 100
    
    retry:
      attempts: 3
      delay: 5
    
    update_interval: 60
    market_hours_only: true
    timeout: 60
  
  alphavantage:
    type: alphavantage
    enabled: false
    api_key: ${ALPHAVANTAGE_API_KEY:}
    rate_limit: 5  # calls per minute
    data_format: json
  
  yahoo:
    type: yahoo
    enabled: false
    threads: 5
    chunk_size: 100
    timeout: 30
    retry:
      attempts: 3

# Logging configuration
logging:
  level: INFO
  format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
  
  # File logging
  file:
    enabled: true
    path: logs/trading_platform.log
    max_size: 10485760  # 10MB
    backup_count: 5
  
  # Console logging
  console:
    enabled: true
    colorize: true

# Feature flags
features:
  real_time_alerts: false
  backtesting: true
  paper_trading: false
  advanced_analytics: true
  market_internals: true
  plurality_wamrs: true

# API configurations
apis:
  rest:
    enabled: false
    host: 0.0.0.0
    port: 8000
    cors_enabled: true
    rate_limit: 100  # requests per minute
  
  websocket:
    enabled: false
    host: 0.0.0.0
    port: 8001

# Performance settings
performance:
  cache:
    enabled: true
    ttl: 300  # seconds
    max_size: 1000
  
  threading:
    max_workers: 10
    queue_size: 100
  
  batch_processing:
    enabled: true
    batch_size: 1000

# Security settings
security:
  secret_key: ${TRADING_SECRET_KEY:change-me-in-production}
  token_expiry: 3600  # seconds
  password_min_length: 8
  max_login_attempts: 5

# Monitoring
monitoring:
  metrics:
    enabled: false
    export_interval: 60
  
  health_check:
    enabled: true
    endpoint: /health
    interval: 30